#!/bin/sh

. config/options

$SCRIPTS/checkdeps build || exit 1

rm -rf $XZ_NAME $TARBALL_DIR
mkdir -p $TARBALL_DIR

[ "$NOROOTFS" = 1 ] || $SCRIPTS/rootfs

cp -PR $ROOTFS/* $TARBALL_DIR

. $CONFIG_MACHINE/meta

if [ -n "$MACHINE_XLOADER_CONFIG" ]; then
  $SCRIPTS/installdev x-loader
  mkdir -p $TARBALL_DIR/boot
  cp -P $ROOT/$TOOLCHAIN/share/x-loader/* $TARBALL_DIR/boot
fi

if [ -n "$MACHINE_UBOOT_CONFIG" ]; then
  $SCRIPTS/installdev u-boot
  mkdir -p $TARBALL_DIR/boot
  cp -PR $ROOT/$TOOLCHAIN/share/u-boot/* $TARBALL_DIR/boot
fi

tar cpaf $XZ_NAME -C $TARBALL_DIR .

if [ "$TARGET_MACHINE" = "tbs2910" ]; then
   #mkdir -p $BINROOT/install_dir
   cp -r $CONFIG_MACHINE/TBS-MatrixTV $BINROOT
   cp $ROOT/$TOOLCHAIN/share/u-boot/u-boot.bin "$BINROOT/TBS-MatrixTV/Profiles/MX6Q Linux Update/OS Firmware/files/u-boot-mx6q-sabresd.bin"
   cp $TARBALL_DIR/boot/uImage "$BINROOT/TBS-MatrixTV/Profiles/MX6Q Linux Update/OS Firmware/files/"
   mv $XZ_NAME "$BINROOT/TBS-MatrixTV/Profiles/MX6Q Linux Update/OS Firmware/files/"
   XZ_NAME=$TARBALL_NAME.xz
   tar cpaf $XZ_NAME -C $BINROOT/TBS-MatrixTV .
   rm -rf $BINROOT/TBS-MatrixTV
fi

rm -rf $TARBALL_DIR

exit 0
